<?php
//It's file is part of "Simple CDR View"
//Licensed GPL2 (see LICENSE)
//(c)2010-2012 Oleg Kuchenko


$ru = array (
"sitetitle" => "Simple CDR Viewer" ,
"welcome" => "Здравствуйте" ,
"exit" => "Выход",
"name" => "Имя",
"enter" => "Войти",
"refresh" => "Обновить",
"yourole" => "Ваша роль",
"menulist" => "Список",
"list" => "Список",
"panel" => "Панель",
"number" => "Номер",
"current-status" => "Текущий статус",
"amount-requests" => "Количество заявок",
"champing-type" => "Тип кампании",
"upload-media-info" => "Необходимо заполнить все поля. Формат файла - gsm",
"upload-base-info" => "Необходимо заполнить все поля. Формат базы - csv с одним столбцом без заголовков",
"upload-error" => "Ошибка загрузки файла",
"upload-exist" => "Файл уже существует",
"upload-stored" => "Файл сохранён",
"upload-encoding" => "Попытка перекодирования файла в gsm формат",
"upload-encoding-fail" => "Перекодирования произошло с ошибкой",
"upload-invalid-type" => "Неверный тип файла",
"form-not-field" => "Не все поля формы корректно заполнены",
"create-champing" => "Создать кампанию",
"numbers-in-base" => "Номеров в базе",
"new-champing" => "Новая",
"state" => "Статус",
"state-update-ok" => "Статус обновлён успешно",
"active-request" => "Активные заявки",
"all-request" => "Все заявки",
"base-limit" => "Количество попыток дозвона",
"checkname" => "Проверка имени",
"super" => "Супервизор",
"allow" => "Разрешено",
"start" => "Старт",
"stop" => "Стоп",
"clear" => "Очистить",
"import" => "Импорт",
"deny" => "Запрещено",
"delete-ok" => "Успешно удалено",
"add-ok" => "Успешно добавлено",
"admin" => "Администратор",
"user" => "Пользователь",
"detale" => "Детально",
"calldate" => "Дата звонка",
"activity" => "Активность",
"macros" => "Приложения",
"macro" => "Приложение",
"macrodata" => "Данные",
"defaultchannel" => "Канал",
"callerid" => "cid",
"waitmsec" => "Ожидание между заявками",
"params" => "Параметры",
"limitcnt" => "Количество одновременных",
"usedfilters" => "Использованные фильтры",
"src" => "Источник",
"dst" => "Получатель",
"duration" => "Длительность",
"billsec" => "Соединение",
"disposition" => "Результат",
"record" => "Запись",
"clid" => "Определитель",
"context" => "Контекст",
"srcchannel" => "Канал источник",
"dstchannel" => "Канал назначения",
"lastapp" => "Последнее приложения",
"lastappdata" => "Данные",
"date" => "Дата",
"ANSWERED" => "ОТВЕЧЕН",
"NO ANSWER" => "НЕ ОТВЕЧЕН",
"BUSY" => "ЗАНЯТ",
"FAILED" => "ОШИБКА",
"extension" => "Номер",
"alldate" => "Весь период",
"begindate" => "Начальная дата",
"enddate" => "Конечная дата",
"Name/username" => "Имя/Имя пользователя",
"Status" => "Статус",
"Host" => "Хост",
"gateway" => "Шлюз",
"timeout" => "Таймаут",
"succes" => "Удачно",
"smserror" => "Ошибка отправки",
"sendingsms" => "Попытка отправить сообщение",
"new-gateway" => "Новый Шлюз",
"create-gateway" => "Создать Шлюз",
"gateways" => "Шлюзы",
"result" => "Результат",
"on" => " на ",
"maxlen-69" => " Максимальная длинна - 69 символов",
"maxlen-6" => " Максимальная длинна - 6 символов",
"reports" => "Отчёты",
"providerproportion" => "Доля провайдеров",
"operatorproportion" => "Доля агентов",
"providerid" => "id провайдера",
"unknown" => "Неизвестно",
"count" => "Количество",
"base" => "База",
"bases" => "Базы",
"champing" => "Кампания",
"champings" => "Кампании",
"active basecalls" => "Активные заявки",
"basecalls" => "Заявки",
"providername" => "Провайдер",
"providerdesc" => "Описание провайдера",
"select" => "Выбрать",
"scenarios" => "Сценарии",
"scenario" => "Сценарий",
"sumsec" => "Сумма (сек)",
"summin" => "Сумма (мин)",
"medialib" => "Медиатека",
"add" => "Добавить",
"delete" => "Удалить",
"rename" => "Переименовать",
"filename" => "Имя файла",
"filesize" => "Размер файла",
"filetype" => "Тип файла",
"description" => "Описание",
"withoutdescription" => "Без описания",
"action" => "Действие",
"address" => "Адрес",
"sms" => "СМС",
"ussd" => "USSD",
"records" => "Записи",
"download" => "Загрузить",
"record" => "Запись",
"port" => "Порт",
"numbers" => "Номера",
"numbers-transform" => "Номера преобразованы в вид: ",
"smstext-transform" => "СМС текст преобразован в вид: ",
"ussdtext-transform" => "USSD запрос преобразован в вид: ",
"numbers-sms-desc" => "Номера без 8-ки, 7-кии прочих преффиксов, разделённые символом точки с запятой",
"smstext" => "СМС-Текст",
"create-sms" => "Создать СМС",
"create-ussd" => "Создать USSD",
"password" => "Пароль"
);

include_once("./etc/setup.php");
if ($lang=="ru"){
    $arr_lang = $ru;
}
else{
    $arr_lang = $en;
}

?>